### 登錄請求

POST http://127.0.0.1:5000/login
Content-Type: application/json

{
  "username": "newuser",
  "password": "newpassword"
}







#測試獲取token
### 受保護的數據請求

GET  http://127.0.0.1:5000/api/subcat/id/10

### 獲取用戶資料
 http://localhost:5000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczMjUwNjEyMywianRpIjoiZTBkYTU4YWItMzVlZC00MmU5LWJjMTktN2EzMzQ0OTEyZDQ1IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6NiwibmJmIjoxNzMyNTA2MTIzLCJjc3JmIjoiNWZjZDJlZTktYTA3Yi00MTY3LWEwNmUtZDZmYzZiOGRhNTY0IiwiZXhwIjoxNzM1MDk4MTIzfQ.iY8cDLAyyHKntmGBvWZ5BBFrIr-6Pjn-4Xu58ao0jiM




GET http://localhost:5000/api/comments/1
